[platformio]
default_envs = waveshare-1_85c

[env]
extra_scripts = pre:scripts/platformio_version.py
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
board = esp32-s3-devkitc-1
monitor_speed = 115200
upload_speed = 921600
lib_extra_dirs = boards
board_build.partitions = partitions.csv
board_upload.flash_size = 16MB
board_build.flash_size = 16MB
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
lib_deps =
    links2004/WebSockets@^2.7.2
    bblanchon/ArduinoJson@^7.4.2

[env:generic-esp32s3]
build_flags =
    ${env.build_flags}
    -DJARVIS_BOARD_GENERIC_ESP32S3=1

[env:waveshare-1_85c]
build_flags =
    ${env.build_flags}
    -DJARVIS_BOARD_WAVESHARE_185C=1
    -DBOARD_HAS_PSRAM
board_build.arduino.memory_type = qio_opi
lib_deps =
    ${env.lib_deps}
    moononournation/GFX Library for Arduino@^1.6.6
    https://github.com/pschatzmann/arduino-audio-driver.git#v0.2.0
