[platformio]
default_envs = waveshare-1_85c

[env]
extra_scripts =
    pre:scripts/platformio_version.py
    pre:scripts/platformio_esp_sr.py
    post:scripts/platformio_websockets_psram.py
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
board = esp32-s3-devkitc-1
monitor_speed = 115200
upload_speed = 921600
lib_extra_dirs = boards
board_build.partitions = partitions.csv
board_upload.flash_size = 16MB
board_build.flash_size = 16MB
build_flags =
    -Iinclude
    -DCORE_DEBUG_LEVEL=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
lib_deps =
    links2004/WebSockets@^2.7.2
    bblanchon/ArduinoJson@^7.4.2

[env:generic-esp32s3]
lib_ignore =
    jarvis-board-waveshare-esp32-s3-touch-lcd-1.85c
    jarvis-board-futureproofhomes-satellite1-1
build_flags =
    ${env.build_flags}
    -DJARVIS_BOARD_GENERIC_ESP32S3=1

[env:waveshare-1_85c]
board_build.partitions = partitions_waveshare_sr.csv
lib_ignore =
    jarvis-board-generic-esp32s3
    jarvis-board-futureproofhomes-satellite1-1
build_flags =
    ${env.build_flags}
    -DJARVIS_BOARD_WAVESHARE_185C=1
    -DBOARD_HAS_PSRAM
    -DARDUINO_PARTITION_esp_sr_16=1
board_build.arduino.memory_type = qio_opi
lib_deps =
    ${env.lib_deps}
    moononournation/GFX Library for Arduino@^1.6.6
    https://github.com/olikraus/U8g2_Arduino.git#2.36.19
    https://github.com/pschatzmann/arduino-audio-driver.git#v0.2.0

[env:satellite1-1]
lib_ignore =
    jarvis-board-generic-esp32s3
    jarvis-board-waveshare-esp32-s3-touch-lcd-1.85c
build_flags =
    ${env.build_flags}
    -DJARVIS_BOARD_FUTUREPROOFHOMES_SATELLITE1_1=1
    -DBOARD_HAS_PSRAM
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = dio
