#pragma once

#if __has_include("local_config.h")
#include "local_config.h"
#endif

#ifndef AIVOICE-SATELLITE_WIFI_SSID
#define AIVOICE-SATELLITE_WIFI_SSID "CHANGE_ME"
#endif
#ifndef AIVOICE-SATELLITE_WIFI_PASSWORD
#define AIVOICE-SATELLITE_WIFI_PASSWORD "CHANGE_ME"
#endif

#ifndef AIVOICE-SATELLITE_CORE_HOST
#define AIVOICE-SATELLITE_CORE_HOST "172.16.2.30"
#endif
#ifndef AIVOICE-SATELLITE_CORE_PORT
#define AIVOICE-SATELLITE_CORE_PORT 8081
#endif
#ifndef AIVOICE-SATELLITE_CORE_PATH
#define AIVOICE-SATELLITE_CORE_PATH "/api/v1/voice/live"
#endif
#ifndef AIVOICE-SATELLITE_CORE_TLS
#define AIVOICE-SATELLITE_CORE_TLS 0
#endif
#ifndef AIVOICE-SATELLITE_CORE_TOKEN
#define AIVOICE-SATELLITE_CORE_TOKEN ""
#endif

#ifndef AIVOICE-SATELLITE_SATELLITE_ID
#define AIVOICE-SATELLITE_SATELLITE_ID "satellite-esp32-01"
#endif
#ifndef AIVOICE-SATELLITE_SATELLITE_NAME
#define AIVOICE-SATELLITE_SATELLITE_NAME "ESP32 Satellite"
#endif

#ifndef AIVOICE-SATELLITE_RECORD_MS
#define AIVOICE-SATELLITE_RECORD_MS 8000
#endif

// Optional local end-of-speech detection. Recording always stops at
// AIVOICE-SATELLITE_RECORD_MS even when no speech/silence transition was detected.
#ifndef AIVOICE-SATELLITE_SILENCE_DETECTION
#define AIVOICE-SATELLITE_SILENCE_DETECTION 0
#endif
#ifndef AIVOICE-SATELLITE_SILENCE_THRESHOLD
#define AIVOICE-SATELLITE_SILENCE_THRESHOLD 500
#endif
#ifndef AIVOICE-SATELLITE_SILENCE_TIMEOUT_MS
#define AIVOICE-SATELLITE_SILENCE_TIMEOUT_MS 900
#endif
#ifndef AIVOICE-SATELLITE_SILENCE_MIN_SPEECH_MS
#define AIVOICE-SATELLITE_SILENCE_MIN_SPEECH_MS 250
#endif
#ifndef AIVOICE-SATELLITE_SILENCE_ARM_MS
#define AIVOICE-SATELLITE_SILENCE_ARM_MS 300
#endif

// ESP32-S3 WakeNet test wake word. The first implementation intentionally
// uses Espressif's bundled "Hi ESP" model (wn9_hiesp).
#ifndef AIVOICE-SATELLITE_WAKEWORD_ENABLED
#define AIVOICE-SATELLITE_WAKEWORD_ENABLED 0
#endif
#ifndef AIVOICE-SATELLITE_WAKEWORD_NAME
#define AIVOICE-SATELLITE_WAKEWORD_NAME "Hi ESP"
#endif
#ifndef AIVOICE-SATELLITE_AUDIO_RATE
#define AIVOICE-SATELLITE_AUDIO_RATE 16000
#endif
#ifndef AIVOICE-SATELLITE_AUDIO_CHANNELS
#define AIVOICE-SATELLITE_AUDIO_CHANNELS 1
#endif
#ifndef AIVOICE-SATELLITE_AUDIO_CHUNK_MS
#define AIVOICE-SATELLITE_AUDIO_CHUNK_MS 20
#endif

#ifndef AIVOICE-SATELLITE_AUTO_TTS
#define AIVOICE-SATELLITE_AUTO_TTS 1
#endif

// TTS quality requested from Ai-Voice-Satellite Core for auto-TTS sessions.
// User-facing values: low, medium, high. "medium" is translated to
// the Core API quality name "balanced" for compatibility.
#ifndef AIVOICE-SATELLITE_TTS_QUALITY
#define AIVOICE-SATELLITE_TTS_QUALITY "low"
#endif


// Display rotation for boards with a screen. Both degree values and legacy
// Arduino_GFX indices are accepted:
//   0 = default
//   90 or 1 = 90 degrees clockwise
//   180 or 2 = 180 degrees
//   270 or 3 = 270 degrees clockwise
// The Waveshare CST816 touch coordinates are rotated with the display.
#ifndef AIVOICE-SATELLITE_DISPLAY_ROTATION
#define AIVOICE-SATELLITE_DISPLAY_ROTATION 0
#endif

#if AIVOICE-SATELLITE_DISPLAY_ROTATION == 90
#define AIVOICE-SATELLITE_DISPLAY_ROTATION_INDEX 1
#elif AIVOICE-SATELLITE_DISPLAY_ROTATION == 180
#define AIVOICE-SATELLITE_DISPLAY_ROTATION_INDEX 2
#elif AIVOICE-SATELLITE_DISPLAY_ROTATION == 270
#define AIVOICE-SATELLITE_DISPLAY_ROTATION_INDEX 3
#elif (AIVOICE-SATELLITE_DISPLAY_ROTATION >= 0) && (AIVOICE-SATELLITE_DISPLAY_ROTATION <= 3)
#define AIVOICE-SATELLITE_DISPLAY_ROTATION_INDEX AIVOICE-SATELLITE_DISPLAY_ROTATION
#else
#define AIVOICE-SATELLITE_DISPLAY_ROTATION_INDEX 0
#define AIVOICE-SATELLITE_DISPLAY_ROTATION_INVALID 1
#endif

#ifndef AIVOICE-SATELLITE_NTP_SERVER
#define AIVOICE-SATELLITE_NTP_SERVER "pool.ntp.org"
#endif
#ifndef AIVOICE-SATELLITE_TIMEZONE_POSIX
#define AIVOICE-SATELLITE_TIMEZONE_POSIX "CET-1CEST,M3.5.0,M10.5.0/3"
#endif

#ifndef AIVOICE-SATELLITE_WAVESHARE_TOUCH_SWAP_XY
#define AIVOICE-SATELLITE_WAVESHARE_TOUCH_SWAP_XY 0
#endif
#ifndef AIVOICE-SATELLITE_WAVESHARE_TOUCH_INVERT_X
#define AIVOICE-SATELLITE_WAVESHARE_TOUCH_INVERT_X 0
#endif
#ifndef AIVOICE-SATELLITE_WAVESHARE_TOUCH_INVERT_Y
#define AIVOICE-SATELLITE_WAVESHARE_TOUCH_INVERT_Y 0
#endif

#ifndef AIVOICE-SATELLITE_RECONNECT_MS
#define AIVOICE-SATELLITE_RECONNECT_MS 3000
#endif
#ifndef AIVOICE-SATELLITE_WIFI_TIMEOUT_MS
#define AIVOICE-SATELLITE_WIFI_TIMEOUT_MS 20000
#endif

#ifndef AIVOICE-SATELLITE_PROTOCOL_STRUCTURED
#define AIVOICE-SATELLITE_PROTOCOL_STRUCTURED 1
#endif

// Generic ESP32-S3 defaults. Override in local_config.h if needed.
#ifndef AIVOICE-SATELLITE_GENERIC_BUTTON_PIN
#define AIVOICE-SATELLITE_GENERIC_BUTTON_PIN 0
#endif
#ifndef AIVOICE-SATELLITE_GENERIC_MIC_BCLK_PIN
#define AIVOICE-SATELLITE_GENERIC_MIC_BCLK_PIN 4
#endif
#ifndef AIVOICE-SATELLITE_GENERIC_MIC_WS_PIN
#define AIVOICE-SATELLITE_GENERIC_MIC_WS_PIN 5
#endif
#ifndef AIVOICE-SATELLITE_GENERIC_MIC_DATA_PIN
#define AIVOICE-SATELLITE_GENERIC_MIC_DATA_PIN 6
#endif
#ifndef AIVOICE-SATELLITE_GENERIC_MIC_SHIFT
#define AIVOICE-SATELLITE_GENERIC_MIC_SHIFT 14
#endif
#ifndef AIVOICE-SATELLITE_GENERIC_MIC_RIGHT_SLOT
#define AIVOICE-SATELLITE_GENERIC_MIC_RIGHT_SLOT 0
#endif
#ifndef AIVOICE-SATELLITE_GENERIC_SPK_BCLK_PIN
#define AIVOICE-SATELLITE_GENERIC_SPK_BCLK_PIN 15
#endif
#ifndef AIVOICE-SATELLITE_GENERIC_SPK_WS_PIN
#define AIVOICE-SATELLITE_GENERIC_SPK_WS_PIN 16
#endif
#ifndef AIVOICE-SATELLITE_GENERIC_SPK_DATA_PIN
#define AIVOICE-SATELLITE_GENERIC_SPK_DATA_PIN 17
#endif

#ifndef AIVOICE-SATELLITE_WAVESHARE_SPEAKER_VOLUME
#define AIVOICE-SATELLITE_WAVESHARE_SPEAKER_VOLUME 70
#endif
#ifndef AIVOICE-SATELLITE_WAVESHARE_MIC_GAIN
#define AIVOICE-SATELLITE_WAVESHARE_MIC_GAIN 70
#endif

#ifndef AIVOICE-SATELLITE_SEND_HELLO
#define AIVOICE-SATELLITE_SEND_HELLO 0
#endif
